### ISSUE TITLE
自己制作了 GGB 课件，但无法上传到你部署的 GGB 库中

### ISSUE THREAD

**Issue by pimgeek** [rhcad/ggblib#1]
问题地址 - http://rhcad.com/ggblib/#/upload

我很想使用你架设的资源库，我自己制作了 GGB 课件，但无法上传到你部署的 GGB 库中。

[test.zip](https://github.com/rhcad/ggblib/files/138981/test.zip)

具体问题就是，预览效果已经出来，但点击提交按钮没有任何反应，我想登录也不成功，说还在建设中。。。

而且，你 Blog 上的友言插件也可能有点异常，我发出上面的这个问题反馈，它直接在网页上显示：垃圾评论已被屏蔽。。。

**Comment by rhcad** [comment]
我下周增加在线上传功能。

http://rhcad.com/mathvg

谢谢
张云贵

**Comment by rhcad** [comment]
已增加了上传功能，请体验和提建议 http://rhcad.com/mathvg/

**Comment by pimgeek** [comment]
神速啊，我立刻去上传一下，GeoGebra 的官网从京津地区访问速度实在太慢了。
